name: del_pick
description: "Del-Pick Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.3.2
  intl: ^0.18.0
  equatable: ^2.0.7
  shimmer: ^3.0.0
  jwt_decoder: ^2.0.1
  flutter_lints: ^4.0.0
  geolocator: 12.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.14
  dotted_border: ^2.0.3
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.5.0
  mapbox_maps_flutter: ^2.5.2
  flutter_dotenv: ^5.2.1
  image: ^4.1.7
  lottie: ^2.3.2
  geocoding: ^2.1.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.3
  provider: ^6.0.5
  audioplayers: 6.4.0
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.4.0
  geotypes: ^0.0.2
  shared_preferences: ^2.5.3
  http: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  get_storage: ^2.1.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - .env

  uses-material-design: true

  fonts:
    - family: Poppins-Medium
      fonts:
        - asset: "assets/fonts/Poppins-Medium.ttf"
    - family: Poppins-Black
      fonts:
        - asset: "assets/fonts/Poppins-Black.ttf"
    - family: Poppins-BlackItalic
      fonts:
        - asset: "assets/fonts/Poppins-BlackItalic.ttf"
    - family: Poppins-Bold
      fonts:
        - asset: "assets/fonts/Poppins-Bold.ttf"
    - family: Poppins-BoldItalic
      fonts:
        - asset: "assets/fonts/Poppins-BoldItalic.ttf"
    - family: Poppins-Light
      fonts:
        - asset: "assets/fonts/Poppins-Light.ttf"